### ISSUE TITLE
A library used by this sketch is not installed properly

### ISSUE THREAD

**Issue by ikbenmacje** [nok/myo-processing#9]
I just installed The Myo library from Processing (2.2.1) and got the error as shown bellow:
I have also tried to use the version direct from Github the master branch and the development branch with the same result

I am working on OSX 10.9.5
My Myo connect is version: 0.15.0
And the firmware is version: 1.4.1670

```
# Myo v0.8.1.5 - Support: Myo SDK v0.8.1, Firmware v1.1.755, Alpha Firmware v1.1.5 - https://github.com/nok/myo-processing
java.lang.UnsatisfiedLinkError: /private/var/folders/5x/1m0c5dh57tv036wxsx0nn2v80000gp/T/libmyo.jnilib: dlopen(/private/var/folders/5x/1m0c5dh57tv036wxsx0nn2v80000gp/T/libmyo.jnilib, 1): Library not loaded: @rpath/myo.framework/Versions/A/myo
  Referenced from: /private/var/folders/5x/1m0c5dh57tv036wxsx0nn2v80000gp/T/libmyo.jnilib
  Reason: image not found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1894)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at com.thalmic.myo.Hub.copyAndLoadOSXFromTemp(Hub.java:132)
    at com.thalmic.myo.Hub.loadJniResources(Hub.java:54)
    at com.thalmic.myo.Hub.<init>(Hub.java:27)
    at com.thalmic.myo.Hub.<init>(Hub.java:22)
    at de.voidplus.myo.Myo.<init>(Myo.java:98)
    at e1_basic.setup(e1_basic.java:28)
    at processing.core.PApplet.handleDraw(PApplet.java:2361)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Thread.java:745)
Unable to load libmyo.jnilib from directory /var/folders/5x/1m0c5dh57tv036wxsx0nn2v80000gp/T
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application.
```

**Comment by balandinodidonato** [comment]
I had the same problem on OSX 10.8.5
Latest Myo Connect and Firmware.

@ikbenmacje any better by now?

**Comment by bombarie** [comment]
@ikbenmacje @balandinodidonato I don't know if you've fixed this problem yet but I also just encountered it. The fix is to copy myo.framework from your Myo SDK folder into ~/Library/Frameworks. I found this by chance and don't fully understand how this resolves the dependencies but hey, it works.

**Comment by ikbenmacje** [comment]
I Can confirm that with copying the myo.framework to /Library/Frameworks the Myo library for processing now works. I am closing this issue.
